# Generated by Django 3.2.8 on 2021-11-01 18:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0006_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('figcaptureblock', wagtail.core.blocks.StructBlock([('figure', wagtail.images.blocks.ImageChooserBlock(label='Описание картинки')), ('caption', wagtail.core.blocks.CharBlock(label='Картинка'))])), ('rtfblock', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'bold', 'italic', 'ol', 'ul'], help_text='Введите ваш текст', label='Текст')), ('imgblock', wagtail.images.blocks.ImageChooserBlock(help_text='Добавьте изображение', label='Изображение', template='blocks/imgblock.html')), ('youtubeblock', wagtail.embeds.blocks.EmbedBlock(help_text='Встаьте ссылку на видео с Youtube', icon='link', label='Видео'))], blank=True, help_text='Добавляйте и редактируйте необходимые блоки - текст, изображения, видео...', verbose_name='Создание и редактирование статьи'),
        ),
    ]
