# Generated by Django 3.2.8 on 2021-10-29 16:46

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='rtf_body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
