# Generated by Django 3.2.8 on 2021-10-29 19:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0004_homepage_rtf_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фоновая картинка'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='rtf_body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Основной текст'),
        ),
    ]
