# Generated by Django 3.2.8 on 2021-11-04 20:20

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211101_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodytext', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Подвал сайта')),
            ],
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('figcaptureblock', wagtail.core.blocks.StructBlock([('figure', wagtail.images.blocks.ImageChooserBlock(label='Картинка')), ('caption', wagtail.core.blocks.CharBlock(label='Описание картинки'))])), ('rtfblock', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'bold', 'italic', 'ol', 'ul'], help_text='Введите ваш текст', label='Текст')), ('imgblock', wagtail.images.blocks.ImageChooserBlock(help_text='Добавьте изображение', label='Изображение', template='blocks/imgblock.html')), ('youtubeblock', wagtail.embeds.blocks.EmbedBlock(help_text='Встаьте ссылку на видео с Youtube', icon='link', label='Видео'))], blank=True, help_text='Добавляйте и редактируйте необходимые блоки - текст, изображения, видео...', verbose_name='Создание и редактирование статьи'),
        ),
    ]
