# Generated by Django 3.2.8 on 2021-11-04 20:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_footer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Подвал сайта', 'verbose_name_plural': 'Подвалы сайта'},
        ),
        migrations.AlterField(
            model_name='footer',
            name='bodytext',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст подвала сайта'),
        ),
    ]
